apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-dev.yaml
  - namespace-prod.yaml
  - task-manager-dev-application.yaml
  - task-manager-prod-application.yaml

labels:
- includeSelectors: true
  pairs:
    cluster: single-cluster
    managed-by: argocd
