apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learning

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: task-manager
  app.kubernetes.io/managed-by: kustomize
