apiVersion: v1
kind: Service
metadata:
  name: task-manager
  labels:
    app: task-manager
spec:
  type: NodePort
  selector:
    app: task-manager
  ports:
    - port: 80         # Service internal port
      targetPort: 3000 # Pod port
      nodePort: 32080  # Node external port
